/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bathwater.dynamodb.tables;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author rajeshk
 */
@DynamoDBTable(tableName = "drivers")
public class DriverTableItem implements BathwaterItem {
    
    private String driverID;
    
    private String firstName;
    
    private String lastName;
        
    private Address address;
    
    private String emailAddress;
    
    private String phoneNumber;
    
    private String emergencyContactNumber;
    
    private String licenseID;
    
    private String password;
    
    private List<Truck> assignedTrucks;
    
    private List<UserRequest> assignedRequests;
    
    private List<Image> images;
    
    private String token;
    
    private String status;

    @DynamoDBHashKey(attributeName = "driverID")
    @DynamoDBAutoGeneratedKey
    public String getDriverID() {
        return driverID;
    }

    public void setDriverID(String driverID) {
        this.driverID = driverID;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "address")
    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @DynamoDBAttribute(attributeName = "emailAddress")
    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @DynamoDBAttribute(attributeName = "phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "emergencyContactNumber")
    public String getEmergencyContactNumber() {
        return emergencyContactNumber;
    }

    public void setEmergencyContactNumber(String emergencyContactNumber) {
        this.emergencyContactNumber = emergencyContactNumber;
    }

    @DynamoDBAttribute(attributeName = "licenseID")
    public String getLicenseID() {
        return licenseID;
    }

    public void setLicenseID(String licenseID) {
        this.licenseID = licenseID;
    }

    @DynamoDBAttribute(attributeName = "password")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute(attributeName = "assignedTrucks")
    public List<Truck> getAssignedTrucks() {
        return assignedTrucks;
    }

    public void setAssignedTrucks(List<Truck> assignedTrucks) {
        this.assignedTrucks = assignedTrucks;
    }

    @DynamoDBAttribute(attributeName = "assignedRequests")
    public List<UserRequest> getAssignedRequests() {
        return assignedRequests;
    }

    public void setAssignedRequests(List<UserRequest> assignedRequests) {
        this.assignedRequests = assignedRequests;
    }

    @DynamoDBAttribute(attributeName = "images")
    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }

    @DynamoDBAttribute(attributeName = "token")
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    
    @Override
    public void saveItem(DynamoDBMapper mapper) {
        mapper.save(this);
    }

    @Override
    public void deleteItem(DynamoDBMapper mapper) {
        mapper.delete(this);
    }
    
    @DynamoDBDocument
    public static class Address {
        
        private String streetAddress;
        
        private String apartment;
        
        private String city;
        
        private String state;
        
        private String zipCode;

        @DynamoDBAttribute(attributeName = "streetAddress")
        public String getStreetAddress() {
            return streetAddress;
        }

        public void setStreetAddress(String streetAddress) {
            this.streetAddress = streetAddress;
        }

        @DynamoDBAttribute(attributeName = "apartment")
        public String getApartment() {
            return apartment;
        }

        public void setApartment(String apartment) {
            this.apartment = apartment;
        }

        @DynamoDBAttribute(attributeName = "city")
        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        @DynamoDBAttribute(attributeName = "state")
        public String getState() {
            return state;
        }

        public void setState(String state) {
            this.state = state;
        }

        @DynamoDBAttribute(attributeName = "zipcode")
        public String getZipCode() {
            return zipCode;
        }

        public void setZipCode(String zipCode) {
            this.zipCode = zipCode;
        }
        
    }
    
    @DynamoDBDocument
    public static class Truck {
        
        private String date;
        
        private String truckID;
        
        private String licensePlate;
        
        private String status;

        @DynamoDBAttribute(attributeName = "date")
        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        @DynamoDBAttribute(attributeName = "truckID")
        public String getTruckID() {
            return truckID;
        }

        public void setTruckID(String truckID) {
            this.truckID = truckID;
        }

        @DynamoDBAttribute(attributeName = "licensePlate")
        public String getLicensePlate() {
            return licensePlate;
        }

        public void setLicensePlate(String licensePlate) {
            this.licensePlate = licensePlate;
        }

        @DynamoDBAttribute(attributeName = "status")
        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }
        
    }
    
    @DynamoDBDocument
    public static class UserRequest {
        private String userRequestID;
        
        private String status;

        @DynamoDBAttribute(attributeName = "userrequestID")
        public String getUserRequestID() {
            return userRequestID;
        }

        public void setUserRequestID(String userRequestID) {
            this.userRequestID = userRequestID;
        }

        @DynamoDBAttribute(attributeName = "status")
        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }
    }
    
    @DynamoDBDocument
    public static class Image {
        String url;

        @DynamoDBAttribute(attributeName = "url")
        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
    }
}
