/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bathwater.dynamodb.tables;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author rajeshk
 */
@DynamoDBTable(tableName = "inventory")
public class InventoryTableItem implements BathwaterItem {
    
    private String storedItemId;
    
    private List<String> itemCode;
    
    private String storageID;
    
    private String binNumber;
    
    private String categoryID;
    
    private String parentID;
    
    private String ownerID; // actual owner of the item
    
    private String ownerFirstName;
    
    private String ownerLasName;
    
    private String ownerEmail;
    
    private Integer swap;
    
    private String itemName;
    
    private String description;
    
    private String imageName;
    
    private String storageTimestamp;
    
    private String observations;
    
    private List<String> imageURLs;
    
    private String status;
    
    private Integer credits;
    
    private List<SubItem> subItems;
    
    private Lock lock;
    
    private String location;
    
    @DynamoDBHashKey(attributeName = "storedItemId")
    @DynamoDBAutoGeneratedKey
    public String getStoredItemId() {
        return storedItemId;
    }

    public void setStoredItemId(String storedItemId) {
        this.storedItemId = storedItemId;
    }

    @DynamoDBAttribute(attributeName = "itemCode")
    public List<String> getItemCode() {
        return itemCode;
    }

    public void setItemCode(List<String> itemCode) {
        this.itemCode = itemCode;
    }

    @DynamoDBAttribute(attributeName = "storageID")
    public String getStorageID() {
        return storageID;
    }

    public void setStorageID(String storageID) {
        this.storageID = storageID;
    }

    @DynamoDBAttribute(attributeName = "binNumber")
    public String getBinNumber() {
        return binNumber;
    }

    public void setBinNumber(String binNumber) {
        this.binNumber = binNumber;
    }

    @DynamoDBAttribute(attributeName = "categoryID")
    public String getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(String categoryID) {
        this.categoryID = categoryID;
    }

    @DynamoDBAttribute(attributeName = "parentID")
    public String getParentID() {
        return parentID;
    }

    public void setParentID(String parentID) {
        this.parentID = parentID;
    }

    @DynamoDBAttribute(attributeName = "ownerID")
    public String getOwnerID() {
        return ownerID;
    }

    public void setOwnerID(String ownerID) {
        this.ownerID = ownerID;
    }

    @DynamoDBAttribute(attributeName = "ownerFirstName")
    public String getOwnerFirstName() {
        return ownerFirstName;
    }

    public void setOwnerFirstName(String ownerFirstName) {
        this.ownerFirstName = ownerFirstName;
    }

    @DynamoDBAttribute(attributeName = "ownerLastName")
    public String getOwnerLasName() {
        return ownerLasName;
    }

    public void setOwnerLasName(String ownerLasName) {
        this.ownerLasName = ownerLasName;
    }

    @DynamoDBAttribute(attributeName = "ownerEmail")
    public String getOwnerEmail() {
        return ownerEmail;
    }

    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail;
    }

    @DynamoDBAttribute(attributeName = "swap")
    public Integer getSwap() {
        return swap;
    }

    public void setSwap(Integer swap) {
        this.swap = swap;
    }

    @DynamoDBAttribute(attributeName = "itemName")
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "imageName")
    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    @DynamoDBAttribute(attributeName = "storageTimestamp")
    public String getStorageTimestamp() {
        return storageTimestamp;
    }

    public void setStorageTimestamp(String storageTimestamp) {
        this.storageTimestamp = storageTimestamp;
    }

    @DynamoDBAttribute(attributeName = "observations")
    public String getObservations() {
        return observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    @DynamoDBAttribute(attributeName = "imageURLs")
    public List<String> getImageURLs() {
        return imageURLs;
    }

    public void setImageURLs(List<String> imageURLs) {
        this.imageURLs = imageURLs;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "credits")
    public Integer getCredits() {
        return credits;
    }

    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    @DynamoDBAttribute(attributeName = "subItems")
    public List<SubItem> getSubItems() {
        return subItems;
    }

    public void setSubItems(List<SubItem> subItems) {
        this.subItems = subItems;
    }

    @DynamoDBAttribute(attributeName = "lock")
    public Lock getLock() {
        return lock;
    }

    public void setLock(Lock lock) {
        this.lock = lock;
    }

    @DynamoDBAttribute(attributeName = "location")
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    
    
    
    
    @Override
    public void saveItem(DynamoDBMapper mapper) {
        mapper.save(this);
    }

    @Override
    public void deleteItem(DynamoDBMapper mapper) {
        mapper.delete(this);
    }
    
    @DynamoDBDocument
    public static class SubItem {
        
        private String itemCode;
        
        private String itemName;
        
        private String description;
        
        private List<String> imageURLs;
        
        private String status;

        @DynamoDBAttribute(attributeName = "itemCode")
        public String getItemCode() {
            return itemCode;
        }

        public void setItemCode(String itemCode) {
            this.itemCode = itemCode;
        }

        @DynamoDBAttribute(attributeName = "itemName")
        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        @DynamoDBAttribute(attributeName = "description")
        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @DynamoDBAttribute(attributeName = "imageURLs")
        public List<String> getImageURLs() {
            return imageURLs;
        }

        public void setImageURLs(List<String> imageURLs) {
            this.imageURLs = imageURLs;
        }

        @DynamoDBAttribute(attributeName = "status")
        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }
        
        
        
    }
    
    @DynamoDBDocument
    public static class Lock {
        
        String timeStamp;
        
        String userID;

        @DynamoDBAttribute(attributeName = "timeStamp")
        public String getTimeStamp() {
            return timeStamp;
        }

        public void setTimeStamp(String timeStamp) {
            this.timeStamp = timeStamp;
        }

        @DynamoDBAttribute(attributeName = "userID")
        public String getUserID() {
            return userID;
        }

        public void setUserID(String userID) {
            this.userID = userID;
        }
        
    }
    
}
