/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bathwater.dynamodb.tables;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author rajeshk
 */
@DynamoDBTable(tableName = "trucks")
public class TruckTableItem implements BathwaterItem {

    private String truckID;
    
    private String truckType;
    
    private String dealerName;
    
    private DealerAddress dealerAddress;
    
    private String leaseExpiration;
    
    private String status;
    
    private String licensePlate;
    
    private List<Driver> assignedDrivers;
    
    private List<Image> images;

    @DynamoDBHashKey(attributeName = "truckID")
    @DynamoDBAutoGeneratedKey
    public String getTruckID() {
        return truckID;
    }

    public void setTruckID(String truckID) {
        this.truckID = truckID;
    }

    @DynamoDBAttribute(attributeName = "truckType")
    public String getTruckType() {
        return truckType;
    }

    public void setTruckType(String truckType) {
        this.truckType = truckType;
    }

    @DynamoDBAttribute(attributeName = "dealerName")
    public String getDealerName() {
        return dealerName;
    }

    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    @DynamoDBAttribute(attributeName = "dealerAddress")
    public DealerAddress getDealerAddress() {
        return dealerAddress;
    }

    public void setDealerAddress(DealerAddress dealerAddress) {
        this.dealerAddress = dealerAddress;
    }

    @DynamoDBAttribute(attributeName = "leaseExpiration")
    public String getLeaseExpiration() {
        return leaseExpiration;
    }

    public void setLeaseExpiration(String leaseExpiration) {
        this.leaseExpiration = leaseExpiration;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "licensePlate")
    public String getLicensePlate() {
        return licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    @DynamoDBAttribute(attributeName = "assignedDrivers")
    public List<Driver> getAssignedDrivers() {
        return assignedDrivers;
    }

    public void setAssignedDrivers(List<Driver> assignedDrivers) {
        this.assignedDrivers = assignedDrivers;
    }

    @DynamoDBAttribute(attributeName = "images")
    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }
    
    @Override
    public void saveItem(DynamoDBMapper mapper) {
        mapper.save(this);
    }

    @Override
    public void deleteItem(DynamoDBMapper mapper) {
        mapper.delete(this);
    }
    
    @DynamoDBDocument
    public static class Driver {
        
        private String date;
        
        private String driverID;
        
        private String firstName;
        
        private String lastName;

        @DynamoDBAttribute(attributeName = "date")
        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        @DynamoDBAttribute(attributeName = "driverID")
        public String getDriverID() {
            return driverID;
        }

        public void setDriverID(String driverID) {
            this.driverID = driverID;
        }

        @DynamoDBAttribute(attributeName = "firstName")
        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        @DynamoDBAttribute(attributeName = "lastName")
        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }
    }
    
    @DynamoDBDocument
    public static class Image {
        private String url;

        @DynamoDBAttribute(attributeName = "url")
        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
    }
    
    @DynamoDBDocument
    public static class DealerAddress {
        private String streetAddress;
        
        private String city;
        
        private String state;
        
        private String zipCode;
        
        private String phoneNumber;

        @DynamoDBAttribute(attributeName = "streetAddress")
        public String getStreetAddress() {
            return streetAddress;
        }

        public void setStreetAddress(String streetAddress) {
            this.streetAddress = streetAddress;
        }

        @DynamoDBAttribute(attributeName = "city")
        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        @DynamoDBAttribute(attributeName = "state")
        public String getState() {
            return state;
        }

        public void setState(String state) {
            this.state = state;
        }

        @DynamoDBAttribute(attributeName = "zipCode")
        public String getZipCode() {
            return zipCode;
        }

        public void setZipCode(String zipCode) {
            this.zipCode = zipCode;
        }

        @DynamoDBAttribute(attributeName = "phoneNumber")
        public String getPhoneNumber() {
            return phoneNumber;
        }

        public void setPhoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
        }
    }
}
