/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bathwater.dynamodb.tables;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author rajeshk
 */
@DynamoDBTable(tableName = "userrequests")
public class UserRequestTableItem implements BathwaterItem {
    
    private String userRequestID;
    
    private User user;
    
    private Owner itemOwner;
    
    private String type;
    
    private String date;
    
    private String time;
    
    private Driver driver;
    
    private String status;
    
    private List<Item> items;
    
    private List<Bins> bins;
    
    private String signatureURL;
    
    private Integer numberOfItemsToBePicked;
    
    private Long timestamp;
    
    private Integer totalItemsCount;
    
    private String truckId;
    
    private String licensePlate;

    @DynamoDBHashKey(attributeName = "userrequestID")
    @DynamoDBAutoGeneratedKey
    public String getUserRequestID() {
        return userRequestID;
    }

    public void setUserRequestID(String userRequestID) {
        this.userRequestID = userRequestID;
    }

    @DynamoDBAttribute(attributeName = "user")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    @DynamoDBAttribute(attributeName = "type")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @DynamoDBAttribute(attributeName = "date")
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @DynamoDBAttribute(attributeName = "time")
    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @DynamoDBAttribute(attributeName = "itemOwner")
    public Owner getItemOwner() {
        return itemOwner;
    }

    public void setItemOwner(Owner itemOwner) {
        this.itemOwner = itemOwner;
    }

    @DynamoDBAttribute(attributeName = "driver")
    public Driver getDriver() {
        return driver;
    }

    public void setDriver(Driver driver) {
        this.driver = driver;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "items")
    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }

    @DynamoDBAttribute(attributeName = "bins")
    public List<Bins> getBins() {
        return bins;
    }

    public void setBins(List<Bins> bins) {
        this.bins = bins;
    }

    @DynamoDBAttribute(attributeName = "signatureURL")
    public String getSignatureURL() {
        return signatureURL;
    }

    public void setSignatureURL(String signatureURL) {
        this.signatureURL = signatureURL;
    }

    public Integer getTotalItemsCount() {
        return totalItemsCount;
    }

    public void setTotalItemsCount(Integer totalItemsCount) {
        this.totalItemsCount = totalItemsCount;
    }

    public String getTruckId() {
        return truckId;
    }

    public void setTruckId(String truckId) {
        this.truckId = truckId;
    }

    public String getLicensePlate() {
        return licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    
    @DynamoDBAttribute(attributeName = "nItems")
    public Integer getNumberOfItemsToBePicked() {
        return numberOfItemsToBePicked;
    }

    public void setNumberOfItemsToBePicked(Integer numberOfItemsToBePicked) {
        this.numberOfItemsToBePicked = numberOfItemsToBePicked;
    }

    @DynamoDBAttribute(attributeName = "timestamp")
    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public void saveItem(DynamoDBMapper mapper) {
        mapper.save(this);
    }

    @Override
    public void deleteItem(DynamoDBMapper mapper) {
        mapper.delete(this);
    }
 
    @DynamoDBDocument
    public static class User {
        
        private String userID;
        
        private String firstName;
        
        private String lastName;
        
        private String zipCode;
        
        private Address address;
        
        private String phoneNumber;

        @DynamoDBAttribute(attributeName = "address")
        public Address getAddress() {
            return address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }

        @DynamoDBAttribute(attributeName = "userID")
        public String getUserID() {
            return userID;
        }

        public void setUserID(String userID) {
            this.userID = userID;
        }

        @DynamoDBAttribute(attributeName = "firstName")
        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        @DynamoDBAttribute(attributeName = "lastName")
        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        @DynamoDBAttribute(attributeName = "zipCode")
        public String getZipCode() {
            return zipCode;
        }

        public void setZipCode(String zipCode) {
            this.zipCode = zipCode;
        }

        @DynamoDBAttribute(attributeName = "phoneNumber")
        public String getPhoneNumber() {
            return phoneNumber;
        }

        public void setPhoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
        }
        
        @DynamoDBDocument
        public static class Address {
            
            private String streetAddress;
            
            private String apartment;
            
            private String city;
            
            private String state;
            
            private String zipCode;
            
            private String specialInstructions;

            @DynamoDBAttribute(attributeName = "streetAddress")
            public String getStreetAddress() {
                return streetAddress;
            }

            public void setStreetAddress(String streetAddress) {
                this.streetAddress = streetAddress;
            }

            @DynamoDBAttribute(attributeName = "apartment")
            public String getApartment() {
                return apartment;
            }

            public void setApartment(String apartment) {
                this.apartment = apartment;
            }

            @DynamoDBAttribute(attributeName = "city")
            public String getCity() {
                return city;
            }

            public void setCity(String city) {
                this.city = city;
            }

            @DynamoDBAttribute(attributeName = "state")
            public String getState() {
                return state;
            }

            public void setState(String state) {
                this.state = state;
            }

            @DynamoDBAttribute(attributeName = "zipCode")
            public String getZipCode() {
                return zipCode;
            }

            public void setZipCode(String zipCode) {
                this.zipCode = zipCode;
            }

            @DynamoDBAttribute(attributeName = "specialInstructions")
            public String getSpecialInstructions() {
                return specialInstructions;
            }

            public void setSpecialInstructions(String specialInstructions) {
                this.specialInstructions = specialInstructions;
            }
            
        }
        
    }
    
    @DynamoDBDocument
    public static class Owner {
        
        private String ownerID;
        
        private String ownerFirstName;
        
        private String ownerLastName;

        @DynamoDBAttribute(attributeName = "ownerID")
        public String getOwnerID() {
            return ownerID;
        }

        public void setOwnerID(String ownerID) {
            this.ownerID = ownerID;
        }

        @DynamoDBAttribute(attributeName = "ownerFirstName")
        public String getOwnerFirstName() {
            return ownerFirstName;
        }

        public void setOwnerFirstName(String ownerFirstName) {
            this.ownerFirstName = ownerFirstName;
        }

        @DynamoDBAttribute(attributeName = "ownerLastName")
        public String getOwnerLastName() {
            return ownerLastName;
        }

        public void setOwnerLastName(String ownerLastName) {
            this.ownerLastName = ownerLastName;
        }
        
    }
    
    @DynamoDBDocument
    public static class Item {
        private String itemName;
        
        private String brandName;
        
        private String condition;
        
        private String eventualDamages;
        
        private Integer sharable;
        
        List<String> imagesBase64;
        
        List<String> itemCodes;
        
        private String storedItemID;
        
        private List<SubItem> subItems;

        @DynamoDBAttribute(attributeName = "itemName")
        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        @DynamoDBAttribute(attributeName = "brandName")
        public String getBrandName() {
            return brandName;
        }

        public void setBrandName(String brandName) {
            this.brandName = brandName;
        }

        @DynamoDBAttribute(attributeName = "condition")
        public String getCondition() {
            return condition;
        }

        public void setCondition(String condition) {
            this.condition = condition;
        }

        @DynamoDBAttribute(attributeName = "eventualDamages")
        public String getEventualDamages() {
            return eventualDamages;
        }

        public void setEventualDamages(String eventualDamages) {
            this.eventualDamages = eventualDamages;
        }

        @DynamoDBAttribute(attributeName = "sharable")
        public Integer getSharable() {
            return sharable;
        }

        public void setSharable(Integer sharable) {
            this.sharable = sharable;
        }

        @DynamoDBAttribute(attributeName = "images")
        public List<String> getImagesBase64() {
            return imagesBase64;
        }

        public void setImagesBase64(List<String> imagesBase64) {
            this.imagesBase64 = imagesBase64;
        }

        @DynamoDBAttribute(attributeName = "itemCodes")
        public List<String> getItemCodes() {
            return itemCodes;
        }

        public void setItemCodes(List<String> itemCodes) {
            this.itemCodes = itemCodes;
        }

        @DynamoDBAttribute(attributeName = "stroedItemID")
        public String getStoredItemID() {
            return storedItemID;
        }

        public void setStoredItemID(String storedItemID) {
            this.storedItemID = storedItemID;
        }

        @DynamoDBAttribute(attributeName = "subItems")
        public List<SubItem> getSubItems() {
            return subItems;
        }

        public void setSubItems(List<SubItem> subItems) {
            this.subItems = subItems;
        }
    }
    
    @DynamoDBDocument
    public static class SubItem {
        private String itemCode;
        
        private String itemName;
        
        private String description;
        
        private List<String> imageURLs;
        
        private String status;

        @DynamoDBAttribute(attributeName = "itemCode")
        public String getItemCode() {
            return itemCode;
        }

        public void setItemCode(String itemCode) {
            this.itemCode = itemCode;
        }

        @DynamoDBAttribute(attributeName = "itemName")
        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        @DynamoDBAttribute(attributeName = "description")
        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @DynamoDBAttribute(attributeName = "imageURLs")
        public List<String> getImageURLs() {
            return imageURLs;
        }

        public void setImageURLs(List<String> imageURLs) {
            this.imageURLs = imageURLs;
        }
        
        @DynamoDBAttribute(attributeName = "status")
        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }
        
        
        
    }
    
    @DynamoDBDocument
    public static class Bins {
        private String binCode;
        
        private List<String> imageURLs;

        @DynamoDBAttribute(attributeName = "binCode")
        public String getBinCode() {
            return binCode;
        }

        public void setBinCode(String binCode) {
            this.binCode = binCode;
        }

        @DynamoDBAttribute(attributeName = "images")
        public List<String> getImageURLs() {
            return imageURLs;
        }

        public void setImageURLs(List<String> imageURLs) {
            this.imageURLs = imageURLs;
        }
    }
    
    @DynamoDBDocument
    public static class Driver {
        private String driverID;
        
        private String firstName;
        
        private String lastName;

        @DynamoDBAttribute(attributeName = "driverID")
        public String getDriverID() {
            return driverID;
        }

        public void setDriverID(String driverID) {
            this.driverID = driverID;
        }

        @DynamoDBAttribute(attributeName = "firstName")
        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        @DynamoDBAttribute(attributeName = "lastName")
        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }
    }
    
}
