/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bathwater.dynamodb.tables;

import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author rajeshk
 */
@DynamoDBTable(tableName = "users")
public class UserTableItem implements BathwaterItem {

    private String userID;

    private String firstName;

    private String lastName;

    private String emailAddress;

    private String referralCode;

    private String imageURL;

    private String password;

    private String phoneNumber;

    private String stripeID;

    private Integer active;

    private String creationTime;

    private List<Address> address;

    private Membership membership;

    private List<Children> children;

    private List<Requests> pendingRequests;

    private List<StoredItems> storedItems;

    private List<BorrowedItems> borrowedItems;

    private String token;

    private String otp;

    private Integer credits;

    private Wishlist wishlist;

    private List<SwapHistory> swapHistory;

    private List<Notification> notifications;

    private List<Payments> payments;
    
    private String userType;
    
    
    
    
    @DynamoDBHashKey(attributeName = "userID")
    @DynamoDBAutoGeneratedKey
    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "emailAddress")
    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @DynamoDBAttribute(attributeName = "referralCode")
    public String getReferralCode() {
        return referralCode;
    }

    public void setReferralCode(String referralCode) {
        this.referralCode = referralCode;
    }

    @DynamoDBAttribute(attributeName = "imageURL")
    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    @DynamoDBAttribute(attributeName = "password")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute(attributeName = "contactNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "stripeID")
    public String getStripeID() {
        return stripeID;
    }

    public void setStripeID(String stripeID) {
        this.stripeID = stripeID;
    }

    @DynamoDBAttribute(attributeName = "active")
    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    @DynamoDBAttribute(attributeName = "addresses")
    public List<Address> getAddress() {
        return address;
    }

    public void setAddress(List<Address> address) {
        this.address = address;
    }

    @DynamoDBAttribute(attributeName = "creationTime")
    public String getCreationTime() {
        return creationTime;
    }

    public void setCreationTime(String creationTime) {
        this.creationTime = creationTime;
    }

    @DynamoDBAttribute(attributeName = "children")
    public List<Children> getChildren() {
        return children;
    }

    public void setChildren(List<Children> children) {
        this.children = children;
    }

    @DynamoDBAttribute(attributeName = "membership")
    public Membership getMembership() {
        return membership;
    }

    public void setMembership(Membership membership) {
        this.membership = membership;
    }

    @DynamoDBAttribute(attributeName = "pendingRequests")
    public List<Requests> getPendingRequests() {
        return pendingRequests;
    }

    public void setPendingRequests(List<Requests> pendingRequests) {
        this.pendingRequests = pendingRequests;
    }

    @DynamoDBAttribute(attributeName = "storedItems")
    public List<StoredItems> getStoredItems() {
        return storedItems;
    }

    public void setStoredItems(List<StoredItems> storedItems) {
        this.storedItems = storedItems;
    }

    @DynamoDBAttribute(attributeName = "borrowedItems")
    public List<BorrowedItems> getBorrowedItems() {
        return borrowedItems;
    }

    public void setBorrowedItems(List<BorrowedItems> borrowedItems) {
        this.borrowedItems = borrowedItems;
    }

    @DynamoDBAttribute(attributeName = "token")
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
  
    @DynamoDBAttribute(attributeName = "otp")
    public String getOtp() {
        return otp;
    }

    public void setOtp(String otp) {
        this.otp = otp;
    }

    @DynamoDBAttribute(attributeName = "credits")
    public Integer getCredits() {
        return credits;
    }

    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    @DynamoDBAttribute(attributeName = "wishlist")
    public Wishlist getWishlist() {
        return wishlist;
    }

    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }

    @DynamoDBAttribute(attributeName = "swapHistory")
    public List<SwapHistory> getSwapHistory() {
        return swapHistory;
    }

    public void setSwapHistory(List<SwapHistory> swapHistory) {
        this.swapHistory = swapHistory;
    }

    @DynamoDBAttribute(attributeName = "notifications")
    public List<Notification> getNotifications() {
        return notifications;
    }

    public void setNotifications(List<Notification> notifications) {
        this.notifications = notifications;
    }

    @DynamoDBAttribute(attributeName = "payments")
    public List<Payments> getPayments() {
        return payments;
    }

    public void setPayments(List<Payments> payments) {
        this.payments = payments;
    }

    @DynamoDBAttribute(attributeName = "userType")
    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }



    
    
    
    @Override
    public void saveItem(DynamoDBMapper mapper) {
        mapper.save(this);
    }

    @Override
    public void deleteItem(DynamoDBMapper mapper) {
        mapper.delete(this);
    }

    @DynamoDBDocument
    public static class Address {

        private String addressID;

        private String streetAddress;

        private String apartment;

        private String city;

        private String state;

        private String zipCode;

        private String specialInstructions;

        @DynamoDBAttribute(attributeName = "addressID")
        public String getAddressID() {
            return addressID;
        }

        public void setAddressID(String addressID) {
            this.addressID = addressID;
        }

        @DynamoDBAttribute(attributeName = "streetAddress")
        public String getStreetAddress() {
            return streetAddress;
        }

        public void setStreetAddress(String streetAddress) {
            this.streetAddress = streetAddress;
        }

        @DynamoDBAttribute(attributeName = "apartment")
        public String getApartment() {
            return apartment;
        }

        public void setApartment(String apartment) {
            this.apartment = apartment;
        }

        @DynamoDBAttribute(attributeName = "city")
        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        @DynamoDBAttribute(attributeName = "state")
        public String getState() {
            return state;
        }

        public void setState(String state) {
            this.state = state;
        }

        @DynamoDBAttribute(attributeName = "zipcode")
        public String getZipCode() {
            return zipCode;
        }

        public void setZipCode(String zipCode) {
            this.zipCode = zipCode;
        }

        @DynamoDBAttribute(attributeName = "specialInstructions")
        public String getSpecialInstructions() {
            return specialInstructions;
        }

        public void setSpecialInstructions(String specialInstructions) {
            this.specialInstructions = specialInstructions;
        }

    }

    @DynamoDBDocument
    public static class Children {

        private String childID;

        private String name;

        private Integer age;

        private String gender;

        @DynamoDBAttribute(attributeName = "childID")
        public String getChildID() {
            return childID;
        }

        public void setChildID(String childID) {
            this.childID = childID;
        }

        @DynamoDBAttribute(attributeName = "name")
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @DynamoDBAttribute(attributeName = "age")
        public Integer getAge() {
            return age;
        }

        public void setAge(Integer age) {
            this.age = age;
        }

        @DynamoDBAttribute(attributeName = "gender")
        public String getGender() {
            return gender;
        }

        public void setGender(String gender) {
            this.gender = gender;
        }

    }

    @DynamoDBDocument
    public static class Membership {

        private Float price;

        private String interval;

        private String name;

        private String description;

        private Integer points;

        private String stripeSubscriptionID;

        private BillingAddress billingAddress;

        @DynamoDBAttribute(attributeName = "price")
        public Float getPrice() {
            return price;
        }

        public void setPrice(Float price) {
            this.price = price;
        }

        @DynamoDBAttribute(attributeName = "interval")
        public String getInterval() {
            return interval;
        }

        public void setInterval(String interval) {
            this.interval = interval;
        }

        @DynamoDBAttribute(attributeName = "name")
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @DynamoDBAttribute(attributeName = "description")
        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @DynamoDBAttribute(attributeName = "points")
        public Integer getPoints() {
            return points;
        }

        public void setPoints(Integer points) {
            this.points = points;
        }

        @DynamoDBAttribute(attributeName = "stripeSubscriptionID")
        public String getStripeSubscriptionID() {
            return stripeSubscriptionID;
        }

        public void setStripeSubscriptionID(String stripeSubscriptionID) {
            this.stripeSubscriptionID = stripeSubscriptionID;
        }

        @DynamoDBAttribute(attributeName = "billingAddress")
        public BillingAddress getBillingAddress() {
            return billingAddress;
        }

        public void setBillingAddress(BillingAddress billingAddress) {
            this.billingAddress = billingAddress;
        }

        @DynamoDBDocument
        public static class BillingAddress {

            private String streetAddress;

            private String apartment;

            private String city;

            private String state;

            private String zipCode;

            @DynamoDBAttribute(attributeName = "streetAddress")
            public String getStreetAddress() {
                return streetAddress;
            }

            public void setStreetAddress(String streetAddress) {
                this.streetAddress = streetAddress;
            }

            @DynamoDBAttribute(attributeName = "apartment")
            public String getApartment() {
                return apartment;
            }

            public void setApartment(String apartment) {
                this.apartment = apartment;
            }

            @DynamoDBAttribute(attributeName = "city")
            public String getCity() {
                return city;
            }

            public void setCity(String city) {
                this.city = city;
            }

            @DynamoDBAttribute(attributeName = "state")
            public String getState() {
                return state;
            }

            public void setState(String state) {
                this.state = state;
            }

            @DynamoDBAttribute(attributeName = "zipCode")
            public String getZipCode() {
                return zipCode;
            }

            public void setZipCode(String zipCode) {
                this.zipCode = zipCode;
            }
        }

    }

    @DynamoDBDocument
    public static class Requests {

        private String requestID;

        /**
         * Can take values <b>pickup</b>, <b>borrow</b> or <b>retrieve</b>
         */
        private String type;

        private String date;

        private String time;

        private String itemName;

        @DynamoDBAttribute(attributeName = "requestID")
        public String getRequestID() {
            return requestID;
        }

        public void setRequestID(String requestID) {
            this.requestID = requestID;
        }

        @DynamoDBAttribute(attributeName = "type")
        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        @DynamoDBAttribute(attributeName = "date")
        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        @DynamoDBAttribute(attributeName = "time")
        public String getTime() {
            return time;
        }

        public void setTime(String time) {
            this.time = time;
        }

        @DynamoDBAttribute(attributeName = "itemName")
        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }
    }

    @DynamoDBDocument
    public static class StoredItems {

        private String itemID;

        private String name;

        private String description;

        private String categoryID;

        private Status status;

        private Integer credits;

        @DynamoDBAttribute(attributeName = "itemID")
        public String getItemID() {
            return itemID;
        }

        public void setItemID(String itemID) {
            this.itemID = itemID;
        }

        @DynamoDBAttribute(attributeName = "name")
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @DynamoDBAttribute(attributeName = "description")
        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @DynamoDBAttribute(attributeName = "categoryID")
        public String getCategoryID() {
            return categoryID;
        }

        public void setCategoryID(String categoryID) {
            this.categoryID = categoryID;
        }

        @DynamoDBAttribute(attributeName = "status")
        public Status getStatus() {
            return status;
        }

        public void setStatus(Status status) {
            this.status = status;
        }

        @DynamoDBAttribute(attributeName = "credits")
        public Integer getCredits() {
            return credits;
        }

        public void setCredits(Integer credits) {
            this.credits = credits;
        }

        @DynamoDBDocument
        public static class Status {

            private String storageID;

            private String binNumber;

            private String borrowerID;

            /**
             * Can take values of "stored", "borrowed" or "retrieved"
             */
            private String status;

            @DynamoDBAttribute(attributeName = "storageID")
            public String getStorageID() {
                return storageID;
            }

            public void setStorageID(String storageID) {
                this.storageID = storageID;
            }

            @DynamoDBAttribute(attributeName = "binNumber")
            public String getBinNumber() {
                return binNumber;
            }

            public void setBinNumber(String binNumber) {
                this.binNumber = binNumber;
            }

            @DynamoDBAttribute(attributeName = "borrowerID")
            public String getBorrowerID() {
                return borrowerID;
            }

            public void setBorrowerID(String borrowerID) {
                this.borrowerID = borrowerID;
            }

            @DynamoDBAttribute(attributeName = "status")
            public String getStatus() {
                return status;
            }

            public void setStatus(String status) {
                this.status = status;
            }

        }
    }

    @DynamoDBDocument
    public static class BorrowedItems {

        private String itemID;

        private String name;

        private String description;

        private String ownerID;

        @DynamoDBAttribute(attributeName = "itemID")
        public String getItemID() {
            return itemID;
        }

        public void setItemID(String itemID) {
            this.itemID = itemID;
        }

        @DynamoDBAttribute(attributeName = "name")
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @DynamoDBAttribute(attributeName = "description")
        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @DynamoDBAttribute(attributeName = "ownerID")
        public String getOwnerID() {
            return ownerID;
        }

        public void setOwnerID(String ownerID) {
            this.ownerID = ownerID;
        }
    }

    @DynamoDBDocument
    public static class SwapHistory {

        String date;

        Item item;

        String status;

        @DynamoDBAttribute(attributeName = "date")
        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        @DynamoDBAttribute(attributeName = "item")
        public Item getItem() {
            return item;
        }

        public void setItem(Item item) {
            this.item = item;
        }

        @DynamoDBAttribute(attributeName = "status")
        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }

    }

    @DynamoDBDocument
    public static class Item {

        String itemName;
        
        List<String> itemCode;

        List<String> imageURLs;

        String itemID;

        Integer credits;

        String categoryID;

        String parentID;

        @DynamoDBAttribute(attributeName = "itemName")
        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        @DynamoDBAttribute(attributeName = "itemCode")
        public List<String> getItemCode() {
            return itemCode;
        }

        public void setItemCode(List<String> itemCode) {
            this.itemCode = itemCode;
        }

        @DynamoDBAttribute(attributeName = "imageURLs")
        public List<String> getImageURLs() {
            return imageURLs;
        }

        public void setImageURLs(List<String> imageURLs) {
            this.imageURLs = imageURLs;
        }

        @DynamoDBAttribute(attributeName = "itemID")
        public String getItemID() {
            return itemID;
        }

        public void setItemID(String itemID) {
            this.itemID = itemID;
        }

        @DynamoDBAttribute(attributeName = "credits")
        public Integer getCredits() {
            return credits;
        }

        public void setCredits(Integer credits) {
            this.credits = credits;
        }

        @DynamoDBAttribute(attributeName = "categoryID")
        public String getCategoryID() {
            return categoryID;
        }

        public void setCategoryID(String categoryID) {
            this.categoryID = categoryID;
        }

        @DynamoDBAttribute(attributeName = "parentID")
        public String getParentID() {
            return parentID;
        }

        public void setParentID(String parentID) {
            this.parentID = parentID;
        }

    }

    @DynamoDBDocument
    public static class Wishlist {

        Set<String> itemIDs;

        @DynamoDBAttribute(attributeName = "itemIDs")
        public Set<String> getItemIDs() {
            return itemIDs;
        }

        public void setItemIDs(Set<String> itemIDs) {
            this.itemIDs = itemIDs;
        }

    }

    @DynamoDBDocument
    public static class Payments {

        private String cardID;

        private String cardNumber;

        private String expMonth;

        private String expYear;

        private String cardType;

        private String token;

        @DynamoDBAttribute(attributeName = "cardID")
        public String getCardID() {
            return cardID;
        }

        public void setCardID(String cardID) {
            this.cardID = cardID;
        }

        @DynamoDBAttribute(attributeName = "cardNumber")
        public String getCardNumber() {
            return cardNumber;
        }

        public void setCardNumber(String cardNumber) {
            this.cardNumber = cardNumber;
        }

        @DynamoDBAttribute(attributeName = "expMonth")
        public String getExpMonth() {
            return expMonth;
        }

        public void setExpMonth(String expMonth) {
            this.expMonth = expMonth;
        }

        @DynamoDBAttribute(attributeName = "expYear")
        public String getExpYear() {
            return expYear;
        }

        public void setExpYear(String expYear) {
            this.expYear = expYear;
        }

        @DynamoDBAttribute(attributeName = "cardType")
        public String getCardType() {
            return cardType;
        }

        public void setCardType(String cardType) {
            this.cardType = cardType;
        }

        @DynamoDBAttribute(attributeName = "token")
        public String getToken() {
            return token;
        }

        public void setToken(String token) {
            this.token = token;
        }

    }
}
